### ISSUE TITLE
Crash on windows 10 build 

### ISSUE THREAD

**Issue by anandijain** [occ-ai/obs-detect#2]
Hello, and thank you for this wonderful plugin. I just tried cloning and building myself, for Windows 64. 

I built on this commit (master) : ca7a2bb3ab7197fc686072a6b79b1142db12af31

I put the release files in their appropriate (pretty sure) place in `C:\Program Files\obs-studio\`. 
When I started up OBS, everything was good until I added the Detect filter to my webcam and tried to expand the settings, which is when I got the crash. 

I'm hoping to add BlazeFace as another model to this repo in the future, since it seemed to be a pretty small model capable of running in 5ms. 

Here is the log file: 
[2024-03-30 13-51-43.txt](https://github.com/occ-ai/obs-detect/files/14813304/2024-03-30.13-51-43.txt)

Edit: I have tested again and the crash is reproducible locally

**Comment by Mubieox** [comment]
Hello,

On my Windows 10 with version 0.0.1-rc2, I have exactly the same problem when I choose GPU (DirectML) as Inference Device, but if I choose CPU I don't have this problem anymore.

I hope this helps while you're waiting for a fix.

**Comment by royshil** [comment]
@Mubieox can you provide logs please?

**Comment by Mubieox** [comment]
Of course, here are my logs:
[2024-04-09 09-37-08.txt](https://github.com/occ-ai/obs-detect/files/14942235/2024-04-09.09-37-08.txt)
[2024-04-09 09-37-36.txt](https://github.com/occ-ai/obs-detect/files/14942236/2024-04-09.09-37-36.txt)
 @royshil

**Comment by royshil** [comment]
@Mubieox There's an "unknown exception" while loading the model

Does your username for the PC have any special characters? Like non-ascii ?

**Comment by Mubieox** [comment]
My PC username does not contain any special characters. 
@royshil 
Here are my logs when I use CPU as Inference Device:
[2024-04-09 09-38-09.txt](https://github.com/occ-ai/obs-detect/files/14946273/2024-04-09.09-38-09.txt)

**Comment by royshil** [comment]
for some reason directML is rejected on your machine. and i can't say why
but at least it works on the CPU

**Comment by royshil** [comment]
fix #5

**Comment by Mubieox** [comment]
Thank you.

**Comment by anandijain** [comment]
Also fixed for me too, thanks for the speedy fix
