### ISSUE TITLE
Output whether person is detected or not (intermission screen automation)

### ISSUE THREAD

**Issue by Paragrimm** [occ-ai/obs-detect#4]
Hey, thank you for looking into it!

I had the idea to automate the intermission screen via something like:
**"if person is detected -> Hide intermission Screen; else -> Show intermission screen"**

Since I'm using Streamer.Bot, I can watch a file or react on websocket notifications or could handle HTTP Requests. I think that a JSON file etc. would be the best probably, so I can check it every x seconds or something like that :).

Thanks in advance

**Comment by LuminairPrime** [comment]
I love this idea! Detecting the lack of a face would be more reliable than detecting a lack of motion on camera.

**Comment by Paragrimm** [comment]
I hope this feature will be added in the future :D I think this could really improve the stream quality and reliability. And you can do so much more with something like that :D

**Comment by royshil** [comment]
implemented in #16
