### ISSUE TITLE
Request Custom model and mask as options

### ISSUE THREAD

**Issue by ogges** [occ-ai/obs-detect#6]
Hello, 

The Pugin is a brilliant idea. I want to use that for a Twitch stream to make some funny stuff with it. Is it planned to add custom models and masks? Custom models for better detection and mask for example add meme faces as mask.
That would be awesome! 

Greetings and thanks for the answer!

**Comment by royshil** [comment]
@ogges custom model is now available

**Comment by royshil** [comment]
implemented
